- name: Install required packages
  apt:
    name:
      - build-essential
      - ca-certificates
      - clang
      - git
    update_cache: yes
    install_recommends: no
- name: Download Hairgap
  git:
    clone: yes
    dest: /tmp/hairgap
    recursive: yes
    repo: 'https://github.com/cea-sec/hairgap.git'
    update: no
- name:
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/tmp/hairgap/include/wirehair"
    - "/vagrant/{{ platform }}"
- name: Download wirehair
  get_url:
    url: "https://raw.githubusercontent.com/catid/wirehair/master/{{ item }}"
    dest: "/tmp/hairgap/{{ item }}"
    mode: 0o644
  with_items:
    - "include/wirehair/wirehair.h"
    - "gf256.h"
    - "wirehair.cpp"
    - "gf256.cpp"
- name: Make wirehair
  command:
    cmd: "make"
    chdir: "/tmp/hairgap/wirehair"
- name: Make hairgap
  command:
    cmd: make
    chdir: /tmp/hairgap
- name: Copy binaries
  synchronize:
    src: "/tmp/hairgap/{{ item }}"
    dest: "hairgap_binaries/{{ platform }}-{{ item }}"
    mode: pull
  with_items:
    - hairgapr
    - hairgaps
- name: Remove the source
  file:
    path: /tmp/hairgap
    state: absent
